---
name: Práctica Valores y Funciones
locale: es
type: practice
beta: false
teacher_info: ''
language: haskell
id_format: "%05d"
order:
- 201
- 202
- 203
- 205
- 204
- 11
- 12
- 14
- 13
- 15
- 16
- 17
- 18
- 110
- 111
- 112
- 113
private: false
