---
tags:
- pdep
- guia1
- basico
- aritmetica
- recursividad
layout: input_right
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
name: esCuadradoPerfecto
